# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b17da337cb3a21b44305c67ef8f18a2445815d276dc32fea2bcd0b1f9efdec26e4d8b5084048903fe0f67aa3500e730b04beb82826dc55d649d1c9aa80d5503b

test:
  secret_key_base: 6832948c95aa44ee37cf1635d93dee3afbaf0d886a05943174bdd9a24d7f4c3ecfe79fef3db44595f79822f422faa4d273aa376d92ea9a3e412ef0af24508dbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
